### ISSUE TITLE
Make FusionCalibration and FusionMath functions available in Python

### ISSUE THREAD

**Issue by wheaney** [xioTechnologies/Fusion#104]
The exported CPython library doesn't allow access to the FusionMath nor FusionCalibration functions. So I can't do something like the [advanced C examples](https://github.com/xioTechnologies/Fusion/blob/main/Examples/Advanced/main.c) that are calibrating gyro and accel inputs.

**Comment by xioTechnologies** [comment]
[imufusion](https://pypi.org/project/imufusion/) does not implement functions from [FusionMath.h](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionMath.h) because this functionality is already provided by [numpy](https://numpy.org/).  The code below shows how to implement the inertial and magnetic calibration models using numpy.

```
def inertial(uncalibrated, misalignment, sensitivity, offset):
    return (numpy.matrix(misalignment) * numpy.diag(sensitivity) * numpy.array([uncalibrated - offset]).T).A1

def magnetic(uncalibrated, soft_iron_matrix, hard_iron_offset):
    return (numpy.matrix(soft_iron_matrix) * numpy.array([uncalibrated]).T).A1 - hard_iron_offset
```

**Comment by wheaney** [comment]
Ah, I see, thanks!
