### ISSUE TITLE
Can't import imufusion

### ISSUE THREAD

**Issue by IKetchup** [xioTechnologies/Fusion#3]
hello,

When importing imufusion in my code i get the following error :
```
import imufusion
ImportError: numpy.core.multiarray failed to import
```

Did you already encounter this problem or do you have an idea of how to fix it?

**Comment by maynardephd** [comment]
More specifically, the error is:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

I've upgraded to numpy 1.22.3 but I still get this error.

**Comment by xioTechnologies** [comment]
The [CI](https://github.com/xioTechnologies/Fusion/actions) confirms that the Python package installs and runs for all tested OSs and Python versions.

If you are having issues installing the package then please update Python and NumPy to the latest versions.  If you have multiple versions installed then you must make sure you are running the intended version.  If you are still unable to install the Python package then please share all of the following so that we can look into it.

- Error message
- OS (inc. version)
- Python version
- NumPy version

**Comment by IKetchup** [comment]
@maynardephd I managed to install imufusion.

I created a new conda environement with python 3.9 (on windows 10)
- Install numpy 1.22.3
- install imufusion

**Comment by maynardephd** [comment]
Error message: RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
I am running on Windows 10
Python version 3.10.2 using the WinPython distro
numpy 1.22.3

I will try an anaconda install and see how that does.

**Comment by limited-fion** [comment]
I couldn't install the python package too.

Error message:
```
pip install imufusion
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement imufusion
ERROR: No matching distribution found for imufusion
```
OS Version:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Python version: 3.9.2
Numpy version: 1.24.2
