### ISSUE TITLE
Euler angles problem 

### ISSUE THREAD

**Issue by machurapiotrek** [xioTechnologies/Fusion#55]
I'm using MPU6500 to receive raw data form gyro and accelerometer. Sampling frequency is set at 500Hz.

I'm using your python gait-tracking example to data visualisation. With your short_walk.csv file, algorithm works well. 

I can't obtain any good results with my data.
I tilted MPU about 45 degrees and backed to starting position.

As you can see pitch value didn't return to starting position but rose.
I can't figure out what's wrong.

I attach my sample file log.csv. 

[log.csv](https://github.com/xioTechnologies/Fusion/files/10074565/log.csv)
![pitch_problem2](https://user-images.githubusercontent.com/72033834/203523441-11226c9b-5269-41e7-9ba3-fb5389f7f7db.png)
![pitch_problem1](https://user-images.githubusercontent.com/72033834/203523437-0a5c82fb-7407-4eb4-81dd-36b3a6fdb686.png)

**Comment by xioTechnologies** [comment]
In your plot, the angular velocities measured by the gyroscope are in the opposite direction to the changes in inclination indicated by the accelerometer.  It is not clear if you have negated gyroscope measurements, or if the gyroscope axes are misaligned to the accelerometer.

The following two plots below were generated using your data.  The first plot uses negated gyroscope measurements.  The second plot adjusts the gyroscope alignment.  Note that the algorithm determines a lower acceleration error in the second plot.  This suggests that the issue is misalignment and not negation.

![image](https://user-images.githubusercontent.com/1748389/203648786-3d6ce941-117e-432f-8519-22f4ec372167.png)

![image](https://user-images.githubusercontent.com/1748389/203648857-12c535f8-ea22-4adf-9089-eb588b00b388.png)

The gyroscope alignment was adjusted in the second plot using the following line of code, inserted immediately before [line 53](https://github.com/xioTechnologies/Gait-Tracking/blob/main/gait_tracking.py#L53) in [gait_tracking.py](https://github.com/xioTechnologies/Gait-Tracking/blob/main/gait_tracking.py).  Similar results are achieved using `NXNYPZ`, `PZNYPX`, and `NZNYNX`.  You will have to review your design to determine what the actual misalignment is.

`gyroscope[index] = imufusion.axes_swap(gyroscope[index], imufusion.ALIGNMENT_PXNYNZ)`

`.

**Comment by machurapiotrek** [comment]
Thank you for the fast response! I can see clearly now that I need to study the basics of this subject.
